development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://ec2-18-222-195-118.us-east-2.compute.amazonaws.com/faye"
  secret_token: "f572f631c31f67a6e7cd1454269bfcbf74fedbddffa2df94ac2af39e67404d70"
  signature_expiration: 3600 # one hour
